### GENERAL SETTINGS ###

# Outputting
timezone: America/Chicago

# Site settings
title: Huan Weng
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://HuanWeng.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#00b3fe" 
  primary_rgb: "0,179,254" #"0,179,254" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/huan-weng-b8673438
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009960648394

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 1518 Central Street,
    - 3E,
    - 60201, Evanston, IL,
    - United States.

email: huanweng2015@u.northwestern.edu
tel: +1 (781)869-0173


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    